### ISSUE TITLE
int randomized_argmax(const std::vector<T>&) [with T = float]: Assertion `!idxes.empty()' failed.

### ISSUE THREAD

**Issue by BabyCodr** [xuzijian629/combopt-zero#4]
When testing Monte Carlo Tree search at test time as I increase the rollout coefficient the frequency with which this error occurs increases significantly. I understand what is triggering the error but I'm not sure why it is happening, why would there be no indexes that are identified as maximum?

Error:

int randomized_argmax(const std::vector<T>&) [with T = float]: Assertion `!idxes.empty()' failed.

**Comment by xuzijian629** [comment]
Sorry for late response.
Actually I had encountered the same error sometimes during development.
It seems [x[i] == max_value](https://github.com/xuzijian629/combopt-zero/blob/d04c105476fae0ec51a6371bed96961645fd07ed/max-cut/lib/include/util.h#L52) does not hold for some max value due to the precision of float numbers. I think a quick fix would be changing this to `if (abs(x[i] - max_value) < eps)` for some small constant `eps`.

**Comment by xuzijian629** [comment]
no updates. closed
